name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Было "main", меняем на "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/earthquakeproject .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/earthquakeproject
